### ISSUE TITLE
How to extract the attributes?

### ISSUE THREAD

**Issue by czhxiaohuihui** [fawazsammani/look-and-modify#1]
Can you share the code for extracting "attributes" ? Thanks a lot!

"attributes": [the indiced of the 5 extracted attributes]

**Comment by fawazsammani** [comment]
Hi, Sorry for the late reply. You don't have to extract them, you can directly download them from the files I uploaded on the google drive. They are included in the dictionary of caption data. Just convert the indices to the words using the corresponding word map. Originally, i remember using the code [here](https://github.com/gujiuxiang/MIL.pytorch) to extract attributes for the COCO images.
